name: Publish

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - v*.**

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - uses: actions/create-github-app-token@v1.7.0
        id: version-bump-bot-token
        with:
          app-id: ${{ vars.VERSION_BUMP_APP_ID }}
          private-key: ${{ secrets.VERSION_BUMP_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.version-bump-bot-token.outputs.token }}

      # - name: Install Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     registry-url: https://npm.pkg.github.com/

      - name: 🤖 Setup Git user for versioning packages
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@users.noreply.github.com"

      - name: Install dependencies
        run: npm install
        shell: bash

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: 🚀 Nx Release (changelog, version bump and publish packages)
        run: |
          npx nx release --skip-publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ steps.version-bump-bot-token.outputs.token }}

      - name: Commit changes if any
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
